name: tests

on: 
  pull_request:
  release:
    types: [ published ]

env:
  GO_VERSION: 1.17

jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: go test
      run: |
        go fmt ./... & \
        go vet ./... & \
        go test -v ./...
