name: tests

on: 
  pull_request:
  push:
    branches:
      - 'master'
  release:
    types: [ published ]

env:
  GO_VERSION: 1.18

jobs:
  go-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ env.GO_VERSION }}
    - name: Run tests with coverage
      run: |
        go fmt ./... && \
        go vet ./... && \
        go test -race -coverprofile=coverage.out -covermode=atomic ./...
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
